# Generated by Django 5.2.17 on 2026-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Permitir comentrios en este artículo'),
        ),
    ]
