# Generated by Django 5.2.17 on 2026-09-29 20:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción opcional de la categoría'),
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Permitir comentarios en este artículo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición'),
        ),
    ]
