# Generated by Django 5.2.17 on 2026-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Periódico Digital', max_length=100)),
                ('site_url', models.URLField(help_text='URL pública del sitio (ej: https://miperiodico.com)')),
                ('tagline', models.CharField(blank=True, default='Tu fuente de noticias', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('primary_color', models.CharField(default='#607D8B', help_text='Color hexadecimal (ej: #607D8B)', max_length=7)),
                ('allow_registration', models.BooleanField(default=True, help_text='Permitir registro de nuevos usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
