# Generated by Django 5.2.17 on 2026-10-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_category_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="Código del idioma (ej: 'es', 'en', 'fr', 'pt')", max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.category')),
            ],
            options={
                'verbose_name': 'Traducción de Categoría',
                'verbose_name_plural': 'Traducciones de Categorías',
                'unique_together': {('category', 'language_code')},
            },
        ),
    ]
