# Generated by Django 5.2.17 on 2026-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_category_name_en_categorytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='default_language',
            field=models.CharField(default='es', help_text='Idioma por defecto (ej: es, en, fr)', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enable_multilanguage',
            field=models.BooleanField(default=False, help_text='Activar soporte multi-idioma en la aplicación'),
        ),
    ]
