# Generated by Django 5.2.17 on 2026-10-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_siteconfig_default_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text="Código del idioma (ej: 'es', 'en', 'fr', 'pt')", max_length=10)),
                ('title', models.CharField(help_text='Título traducido', max_length=200)),
                ('text', models.TextField(blank=True, help_text='Resumen corto traducido')),
                ('content', models.TextField(blank=True, help_text='Contenido completo traducido')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.post')),
            ],
            options={
                'verbose_name': 'Traducción de Artículo',
                'verbose_name_plural': 'Traducciones de Artículos',
                'unique_together': {('post', 'language_code')},
            },
        ),
    ]
