# Generated by Django 5.2.17 on 2026-10-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_posttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Según sistema')], default='light', help_text='Tema por defecto de la aplicación', max_length=10),
        ),
    ]
